# 简单投资组合配置
# 文件名: simple_config.yaml
# 描述: 最简单的投资组合配置示例
# 策略基本信息
name: "简单投资组合" # 策略名称，用于标识
description: "包含5只知名股票的简单投资组合" # 策略描述
# 投资组合配置

portfolio:
  # 资产列表 - 股票代码列表
  # 支持美股代码，如 AAPL, GOOGL, MSFT 等
  # 建议选择 2-20 只股票进行优化
  tickers:
    - "AAPL" # 苹果公司
    - "GOOGL" # 谷歌母公司
    - "MSFT" # 微软公司
    - "AMZN" # 亚马逊公司
    - "TSLA" # 特斯拉公司
  # 数据时间范围 - 用于计算历史收益率和风险

  # 格式: YYYY-MM-DD
  # 建议使用至少 1 年的数据
  start_date: "2023-01-01" # 数据开始日期
  end_date: "2024-01-01" # 数据结束日期
  # 投资组合总价值 (美元)

  # 用于计算实际可购买的股票数量
  # 建议设置合理的投资金额
  total_portfolio_value: 10000.0
# 资产权重配置 (可选，如果不设置则使用默认值)

asset_weights:
  # 固定权重配置 - 可以指定某些资产的固定权重
  # 格式: {股票代码: 权重}
  # 权重范围: 0.0 - 1.0
  # 示例: {"AAPL": 0.3} 表示固定苹果股票 30% 权重
  fixed_weights: {}
  # 是否允许优化器调整未指定权重的资产

  # true: 允许优化器自动调整权重
  # false: 只使用固定权重，不进行优化
  allow_optimization: true
# 优化策略配置

optimization:
  # 优化策略类型
  # 可选值:
  # - max_sharpe: 最大化夏普比率 (推荐)
  # - min_volatility: 最小化波动率 (低风险)
  # - efficient_risk: 目标风险优化
  # - efficient_return: 目标收益优化
  # - max_quadratic_utility: 最大化二次效用函数
  strategy: "max_sharpe"
  # 目标风险水平 (年化波动率)

  # 范围: 0.0 - 1.0
  # 仅在 strategy 为 efficient_risk 时使用
  # 示例: 0.15 表示目标风险 15%
  target_risk: 0.15
  # 目标收益率 (年化)

  # 范围: 0.0 - 1.0
  # 仅在 strategy 为 efficient_return 时使用
  # 示例: 0.12 表示目标收益 12%
  target_return: 0.12
  # 风险厌恶系数

  # 范围: 0.5 - 3.0
  # 0.5: 风险偏好型投资者
  # 1.0: 中等风险厌恶 (默认值)
  # 2.0: 高度风险厌恶
  # 3.0: 极度风险厌恶
  # 仅在 strategy 为 max_quadratic_utility 时使用
  risk_aversion: 1.0
  # L2正则化参数

  # 范围: 0.1 - 5.0
  # 0.1-0.5: 较弱的正则化，允许更大的权重差异
  # 0.5-2.0: 中等强度，平衡权重分布和收益
  # 2.0-5.0: 较强的正则化，倾向均匀分布
  l2_reg_gamma: 0.8
  # 无风险利率

  # 范围: 0.0 - 1.0
  # 用于计算夏普比率
  # 建议使用当前国债收益率或银行存款利率
  # 示例: 0.03 表示 3%
  risk_free_rate: 0.03
  # 是否启用L2正则化

  # true: 启用正则化，权重分布更均匀
  # false: 不启用正则化，可能产生极端权重
  enable_l2_reg: false
  # 新增：预期收益率计算方法

  expected_return_method: "mean" # 可选: "mean", "capm", "ema"
  # 新增：协方差矩阵计算方法

  covariance_method: "ledoit_wolf" # 可选: "sample", "ledoit_wolf", "exp_cov"
# 约束配置

constraints:
  # 约束策略列表
  # 可选值:
  # - weight_bounds: 权重边界约束 (推荐)
  # - fixed_weights: 固定权重约束
  # - sector_constraints: 行业约束
  # - turnover_constraints: 换手率约束
  strategies:
    - "weight_bounds"
  # 每个资产最小权重

  # 范围: 0.0 - 1.0
  # 确保投资组合不会过度集中
  # 示例: 0.05 表示每个资产最少 5%
  min_weight: 0.10
  # 每个资产最大权重

  # 范围: 0.0 - 1.0
  # 防止单一资产占比过高
  # 示例: 0.40 表示每个资产最多 40%
  # 注意: max_weight 必须大于 min_weight
  max_weight: 0.40
  # 是否启用权重边界约束

  # true: 启用权重约束
  # false: 不启用约束，可能产生极端权重
  enable_weight_bounds: true

# 风险模型配置 (可选，如果不设置则使用默认模型)
# risk_model:
#   # 预期收益率计算函数
#   # 可以指定自定义函数来计算预期收益率
#   expected_returns_func: "calculate_returns"
#   
#   # 协方差矩阵计算函数
#   # 可以指定自定义函数来计算风险模型
#   covariance_func: "calculate_covariance" 
