repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock # Update the uv lockfile
      - id: uv-export # export the uv lockfile to a different format
        args: ["--frozen", "--output-file=requirements.txt"]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 2.14.0
    hooks:
    - id: pretty-format-yaml
      args: [--autofix, --indent, '2']
    - id: pretty-format-toml
      args: [--autofix, --indent, '2']