"""RustFS/S3 artifact materialization for the Bilibili provider."""

from __future__ import annotations

import hashlib
import tempfile
from pathlib import Path
from typing import Protocol
from urllib.parse import urlsplit

from homelab_video_contracts import Artifact


class ArtifactMaterializationError(Exception):
    """Raised when an immutable artifact cannot be materialized safely."""


class ArtifactStager(Protocol):
    """Provider-independent artifact materialization boundary."""

    def materialize(self, artifact: Artifact, *, filename_hint: str) -> Path: ...

    def cleanup(self) -> None: ...


class S3ArtifactStager:
    """Download s3:// artifacts through Airflow's Amazon S3Hook."""

    def __init__(self, *, aws_conn_id: str = "rustfs_default", root: Path | None = None) -> None:
        self.aws_conn_id = aws_conn_id
        self.root = root or Path(tempfile.mkdtemp(prefix="bilibili-artifacts-"))
        self._owned_root = root is None

    def materialize(self, artifact: Artifact, *, filename_hint: str) -> Path:
        parsed = urlsplit(artifact.uri)
        if parsed.scheme != "s3" or not parsed.netloc or not parsed.path.strip("/"):
            raise ArtifactMaterializationError("artifact URI must be a canonical s3:// URI")
        if not filename_hint or Path(filename_hint).name != filename_hint:
            raise ArtifactMaterializationError("filename_hint must be a single safe filename")
        destination = self.root / filename_hint
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            from airflow.providers.amazon.aws.hooks.s3 import S3Hook

            hook = S3Hook(aws_conn_id=self.aws_conn_id)
            hook.download_file(
                key=parsed.path.lstrip("/"),
                bucket_name=parsed.netloc,
                local_path=str(destination.parent),
                preserve_file_name=False,
                use_autogenerated_subdir=False,
            )
        except Exception as error:
            raise ArtifactMaterializationError(f"failed to download artifact {artifact.uri}") from error
        downloaded = destination
        if not downloaded.is_file():
            candidates = list(destination.parent.glob("*"))
            if len(candidates) == 1 and candidates[0].is_file():
                downloaded = candidates[0]
        if not downloaded.is_file():
            raise ArtifactMaterializationError("S3Hook did not produce a local file")
        self._verify(downloaded, artifact)
        return downloaded

    @staticmethod
    def _verify(path: Path, artifact: Artifact) -> None:
        if artifact.size is not None and path.stat().st_size != artifact.size:
            raise ArtifactMaterializationError(f"artifact size mismatch for {artifact.uri}")
        if artifact.sha256:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            if digest != artifact.sha256:
                raise ArtifactMaterializationError(f"artifact sha256 mismatch for {artifact.uri}")

    def cleanup(self) -> None:
        if self._owned_root and self.root.is_dir():
            for child in self.root.iterdir():
                if child.is_file():
                    child.unlink()
            self.root.rmdir()
