name: 🐳 Docker Release

on:
  workflow_call:
    inputs:
      tag:
        description: Existing global release tag to build
        required: true
        type: string
      push_latest:
        description: Also update the latest image tag
        required: false
        type: boolean
        default: true
    secrets:
      PYPI_SERVER_USERNAME:
        required: false
      PYPI_SERVER_PASSWORD:
        required: false
  workflow_dispatch:
    inputs:
      tag:
        description: Existing global release tag to build
        required: true
        type: string
      push_latest:
        description: Also update the latest image tag
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: ShawnDen-coder/repo-scaffold/.github/workflows/reusable-container-release.yaml@0.29.5
    with:
      tag: ${{ inputs.tag }}
      containerfile: ./docker/Dockerfile
      push-latest: ${{ inputs.push_latest }}
    secrets:
      PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
      PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}
