name: lint_and_unittest
on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: task init
      - name: Run lint checks
        id: lint
        run: task lint
      - name: Run test all versions
        run: task test:all
