name: release-build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # 匹配类似 1.0.0, 2.1.3 等格式的标签
permissions:
  contents: write # 用于创建 release
  id-token: write # 用于发布到 PyPI
jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 用于创建 GitHub Release
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: init environment and test
        env:
          UV_INDEX_HOMELAB_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
          UV_INDEX_HOMELAB_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}
        run: |
          task init # 初始化项目环境
          task lint # 运行代码检查
          task test:all # 运行所有测试
      - name: Publish to PyPI Server
        env:
          PYPI_SERVER_USERNAME: ${{ secrets.PYPI_SERVER_USERNAME }}
          PYPI_SERVER_PASSWORD: ${{ secrets.PYPI_SERVER_PASSWORD }}
        run: task deploy:pypi-server
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
